### ISSUE TITLE
downloadwget.vbs does not downloads wget

### ISSUE THREAD

**Issue by V1q** [MarioMasta64/SteamPortable#1]
Every time I run launcher.bat an error occurs. It says that replacer.bat file can't be found.
I figured out that the reason is that calling downloadwget.vbs script doesn't download wget properly.
There is no output from the script itself, but I attach output of the whole launcher.bat :[launcherOutput.txt](https://github.com/MarioMasta64/SteamPortable/files/1659045/launcherOutput.txt).
I run the script on windows 10, 64 bit, and the script is located on a pendrive.
How can I debug this problem?

**Comment by MarioMasta64** [comment]
you cant, this is an issue for everyone, btw the project has been merged into https://github.com/MarioMasta64/EverythingPortable/releases/latest/ please use that instead.
